language:
 - node_js
 - python

python:
 - '3'

node_js:
 - '10'

services:
 - docker

stages:
  - name: hello
    script:
      - echo "hello"
  - name: world
    if: branch = master
    script:
      - echo "world"
