language:
 - node_js
 - python

python:
 - '3'

node_js:
 - '10'

services:
 - docker

stages:
  - name: test
    script:
      - echo "test"
  - name: deploy
    if: branch = master
    script:
      - echo "deploy"
